sudo: required

services:
    - docker

before_install:
    - docker build -t rohitbacknan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true  rohitbacknan/docker-react npm run test -- --coverage
